#!/usr/bin/env bash
# transfer a file from our client to a server
len=$#
err_mess="Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"

if [ "$len" -lt 3 ]
then
    echo "$err_mess"
elif [ "$len" -lt 4 ]
then
    scp "$1" "$3"@"$2":~/ -i "$4" -o StrictHostKeyChecking=no
else
    scp "$1" "$3"@"$2":~/ -o StrictHostKeyChecking=no
fi
   
       
