#!/usr/bin/env bash
# transfer a file from our client to a server
len=$#
err_mess="Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"

if [ "$len" -ne 4 ]
then
    echo "$err_mess"
else
    scp "$1" "$3"@"$2":~/ -i "$4"
fi
   
       
