#!/usr/bin/env bash
# install nginx web server
sudo apt-get -y update
sudo apt-get -y install nginx
sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'
sudo sed -i '/server_name _;/a\\tlocation \/redirect_me {\n\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}' /etc/nginx/sites-availables/default
service nginx start
