#!/usr/bin/env bash
# install nginx web server
sudo apt-get -y update
sudo apt-get -y install nginx
sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'
sudo sed -i '/server_name _;/a\\tlocation \/redirect_me {\n\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}' /etc/nginx/sites-available/default
sudo sed -i "/server_name _;/a\location @404 {\n\treturn 404 \"Ceci n'est pas une page\";\n\t}" /etc/nginx/sites-available/default
sudo sed -i "s/=404/@404/g" /etc/nginx/sites-available/default
service nginx start
