#!/usr/bin/env bash
# install and conf HAproxy load balancer
sudo apt -y update
sudo apt -y install haproxy
sudo echo -e '\n\nfrontend enter-http\n\tbind *:80\n\tdefault_backend servers\n\nbackend servers\n\tbalance roundrobin\n\tserver web-01 35.168.2.45:80 check\n\tserver web-02 54.172.171.220:80 check\n' >> /etc/haproxy/haproxy.cfg
sudo service haproxy start
