#!/usr/bin/env bash
# Print 'Best School' 1- times using while
#+and changes the the 9th to 'Hi'
i=0
while (("$i" < 10))
do
    if (("$i" != ((9 - 1))))
    then
	echo 'Best School'
    else
	echo 'Hi'
    fi
    i=$((i + 1))
done
