#!/usr/bin/env bash
# Print 'Best School' 1- times using while
#+and changes the the 9th to 'Hi'
i=0
while (("$i" < 10))
do
    if (("$i" == 3)); then
	echo 'bad luck'
    elif (("$i" == 7)); then
	echo 'good luck'
    else
	echo 'Best School'
    fi
    i=$((i + 1))
done
