#!/usr/bin/env bash
# Print the content of the current working directory
# in a list format
# only the part after the dash is printed
command="$(ls)"
for file in $command; do
    echo "$file" | cut -d "-" -f2
done
