#!/usr/bin/env bash
# change nginx
sudo chown -R nginx:nginx /var/www/html
sudo chmod -R 755 /var/www/html
sudo sed -i '1i user nginx;/n' /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo service nginx restart
